### ISSUE TITLE
Conda Package Manager breaks Cyclus

### ISSUE THREAD

**Issue by robfairh** [pyne/pyne#1185]
When installing Cyclus dependencies using conda following the instructions on:
https://github.com/cyclus/cyclus and then installing pyne using conda package manager ``` conda install -c conda-forge pyne ``` causes Cyclus to stop working.

This is the message error passed by Cyclus when trying to run it after installing pyne:
```
cyclus: error while loading shared libraries: libhdf5_cpp.so.103: cannot open shared object file: No such file or directory
```

I think the cause is that the conda package manager is using older versions of some of cyclus dependencies. This is the message passed on terminal when installing pyne:

The following packages will be DOWNGRADED:

  boost-cpp                            1.69.0-h11c811c_1000 --> 1.66.0-1
  coincbc                  2.9.9-blas_openblash0f40ac4_1002 --> 2.9.9-blas_openblash35bd731_1002
  hdf5                           1.10.5-nompi_h3c11f04_1103 --> 1.10.1-2
  numpy                 1.16.2-py36_blas_openblash1522bff_0 --> 1.15.2-py36_blas_openblashd3ea46f_1
  openblas                              0.3.3-h9ac9557_1001 --> 0.2.20-8
  pytables                             3.5.2-py36h9f153d1_2 --> 3.4.4-py36_8
  scipy                  1.2.1-py36_blas_openblash1522bff_0 --> 1.1.0-py36_blas_openblash7943236_201

I am working on Ubuntu 18.04 LTS

**Comment by bam241** [comment]
@bam241 believe `Conda` is slowly trying to kill him, in a very slow and painful way....

where did you get you cyclus install from ?
- if you compiled it form source, try to recompile/install `cyclus`
- if you got a pre-compiled version from conda try to install Pyne and cyclus with the same command line

**Comment by robfairh** [comment]
I compiled Cyclus from source. After installing Pyne, I recompiled it and this is the error message I got:
```
[ 88%] Building CXX object cli/CMakeFiles/cyclus_unit_tests.dir/cyclus_unit_test_driver.cc.o
[ 88%] Linking CXX executable ../bin/cyclus_unit_tests
/home/arfc/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../lib/libcyclus.so: undefined reference to `boost::archive::xml_oarchive_impl<boost::archive::xml_oarchive>::save(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/arfc/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../lib/libcyclus.so: undefined reference to `boost::archive::xml_iarchive_impl<boost::archive::xml_iarchive>::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
collect2: error: ld returned 1 exit status
make[2]: *** [cli/CMakeFiles/cyclus_unit_tests.dir/build.make:1234: bin/cyclus_unit_tests] Error 1
make[1]: *** [CMakeFiles/Makefile2:1422: cli/CMakeFiles/cyclus_unit_tests.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
Traceback (most recent call last):
  File "install.py", line 223, in <module>
    main()
  File "install.py", line 219, in main
    install_cyclus(args)
  File "install.py", line 106, in install_cyclus
    shell=(os.name == 'nt'))
  File "/home/arfc/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.

```

**Comment by bam241** [comment]
The problem there is the PyNE you are trying to install is 2years old.
The issue you have is on Boost, that (from what I seen online) seems to not have been compiled with c++11....

my advice there is to install Pyne from source...

**Comment by robfairh** [comment]
Will do! Thanks. Should we close the issue then?

**Comment by bam241** [comment]
I don't know...

**Comment by gwenchee** [comment]
This is fixed by installing from source instead: https://github.com/pyne/pyne/issues/1186

**Comment by gwenchee** [comment]
@robfairh close this issue?

**Comment by robfairh** [comment]
This issue can be avoided installing PyNE from source.

**Comment by gonuke** [comment]
Thanks for closing this, but I just realized that Cyclus does not depend on PyNE.  We probably should have flagged that from the beginning...

Why do you need to have PyNE at all to install Cyclus?

**Comment by robfairh** [comment]
I probably did not describe the issue properly. The problem was the following:
- Cyclus dependencies were installed using conda
- Cyclus was installed from source
- Cyclus was working properly
- pyne was installed using conda
- pyne was working properly
- Cyclus stopped working
