### ISSUE TITLE
Compatibility with hdf5 1.12.0

### ISSUE THREAD

**Issue by bam241** [pyne/pyne#1368]
I did not do extensive test, but PyNE might not be compatible with hdf5 1.12.
I saw this error when trying to compile a amalgamated version of PyNE (dagmc's one) against it...
```
pyne.cpp:14367:12: error: no matching function for call to 'H5Oget_info_by_name3'
  status = H5Oget_info_by_name(db, path.c_str(), &path_info, H5P_DEFAULT);
           ^~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/hdf5/1.12.0_1/include/H5version.h:772:31: note: expanded from macro 'H5Oget_info_by_name'
  #define H5Oget_info_by_name H5Oget_info_by_name3
```

**Comment by bam241** [comment]
this call is made from `Material.cpp` `nt pyne::Material::detect_hdf5_layout(hid_t db, std::string path)`

**Comment by gonuke** [comment]
What about this: https://github.com/pyne/pyne/pull/1220

**Comment by gonuke** [comment]
Or this: #1247

**Comment by bam241** [comment]
this didn't fix the amalgamated version.
The problem is we have to translate that flag in all the project depending on PyNE amalgamation.

I am not sure those solution are the best for maintainability...

Thx for the tip tho

**Comment by gonuke** [comment]
We now build with HDF 1.12 routinely.  Marking this as resolved.  I may create a new ticket about testing a build of amalgamated pyne.
